name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar ambiente virtual
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip

      - name: Gerar e instalar dependências
        run: |
          pip freeze > requirements.txt
          pip install -r requirements.txt

      - name: Instalar pytest
        run: |
          pip install pytest

      - name: Executar testes
        run: pytest